const cookieParser = require("cookie-parser");
const express = require("express");
const app = express();
const PORT = 8080; // default port 8080

function generateRandomString() {
  let result = Math.random().toString(36).substring(2, 8);
  return result;
}

app.set("view engine", "ejs");
app.use(express.urlencoded({ extended: true })); // populates req.body - express's "body parser"
app.use(cookieParser()); // populates req.cookies

const urlDatabase = {
  "b2xVn2": "http://www.lighthouselabs.ca",
  "9sm5xK": "http://www.google.com"
};

const users = {
  abc: {
    id: "abc",
    email: "a@a.com",
    password: "1234"
  },
  def: {
    id: "def",
    email: "b@b.com",
    password: "5678"
  }
};

app.listen(PORT, () => {
  console.log(`Example app listening on port ${PORT}!`);
});


app.get("/urls", (req, res) => {
  const templateVars = {
    urls: urlDatabase,
    user: users[req.cookies.user_id]
  };
  res.render("urls_index", templateVars);
});


app.get("/urls/new", (req, res) => {
  // If user not logged in, redirect to login page
  const u_id = req.cookies.user_id;
  if (!u_id) {
    res.redirect("/login");
  }
  // If user logged in, render urls_new template
  const templateVars = {
    user: users[req.cookies.user_id]
  };
  res.render("urls_new", templateVars);
});

app.get("/urls/:id", (req, res) => {
  const templateVars = {
    id: req.params.id,
    longURL: urlDatabase[req.params.id],
    user: users[req.cookies.user_id]
  };
  res.render("urls_show", templateVars);
});

app.post("/urls", (req, res) => {
  // If user not logged in, respond with error
  const u_id = req.cookies.user_id;
  if (!u_id) {
    return res.status(400).send("Must be logged in to shorten URLs.");
  }
  // If user logged in, allow interaction with server
  const shortURL = generateRandomString();
  console.log(req.body); // Log the POST request body to the console
  console.log(shortURL); // log the shortURL (generated by random string) to the console
  const longURL = req.body.longURL; // key-value pair is being saved to the urlDatabase
  urlDatabase[shortURL] = longURL;
  res.redirect(`/urls/${shortURL}`); // redirect to /urls/:id
});

app.get("/u/:id", (req, res) => {
  let id = req.params.id;
  const longURL = urlDatabase[id];
  res.redirect(longURL);
});

app.post("/urls/:id/delete", (req, res) => {
  let id = req.params.id;
  delete urlDatabase[id];
  res.redirect("/urls");
});

app.post("/urls/:id", (req, res) => {
  let id = req.params.id;
  const longURL = req.body.longURL;
  urlDatabase[id] = longURL;
  res.redirect("/urls");
});

app.get("/login", (req, res) => {
  // Check for existing cookie (user logged in?)
  const u_id = req.cookies.user_id;
  if (u_id) {
    res.redirect("/urls");
  }
  // Render login page if user not logged in
  const templateVars = {
    user: users[req.cookies.user_id]
  };
  res.render("login", templateVars);
});

app.post("/login", (req, res) => {
  const email = req.body.email;
  const password = req.body.password;
  // Is email already registered?
  let foundUser = null;
  for (const u_id in users) {
    const user = users[u_id];
    if (user.email === email) {
      foundUser = user;
    }
  }
  // If email is not registered:
  if (!foundUser) {
    return res.status(403).send("Email is not registered.");
  }
  // If password does not match:
  if (foundUser.password !== password) {
    return res.status(403).send("Password is incorrect.");
  }

  res.cookie("user_id", foundUser.id);
  res.redirect("/urls");
});

app.post("/logout", (req, res) => {
  res.cookie("user_id", users[req.cookies.user_id]);
  res.clearCookie("user_id", users[req.cookies.user_id]);
  res.redirect("/login");
});

app.get("/register", (req, res) => {
  // Check for existing cookie (user logged in?)
  const u_id = req.cookies.user_id;
  if (u_id) {
    res.redirect("/urls");
  }
  // Render register page if user not logged in
  const templateVars = {
    user: users[req.cookies.user_id]
  };
  res.render("registration", templateVars);
});

app.post("/register", (req, res) => {
  const email = req.body.email;
  const password = req.body.password;

  if (email === '' || password === '') {
    return res.status(400).send("Please provide a username and password");
  }

  for (const u_id in users) {
    const user = users[u_id];
    if (user.email === email) {
      return res.status(400).send("Email already exists");
    }
  }

  const id = generateRandomString();
  const newUser = {
    id: id,
    email: email,
    password: password
  };
  users[id] = newUser;
  res.cookie("user_id", id);

  console.log(users);
  res.redirect("/urls");
});

